import Head from "next/head";
import Slider from "@/components/Slider";
import Featured from "@/components/Featured";
import Offer from "@/components/Offer";

export default function Home() {
  return (
    <>
      <Head>
        <title>FAST FOOD</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Slider />
        <Featured />
        <Offer />
      </main>
    </>
  );
}
